### PR TITLE
No methods testcase, fix debug message, drop Appveyor

### PR DESCRIPTION
**Pull request by omus**
A couple changes in one PR:

- Adds a more obvious testcase for: https://github.com/invenia/Mocking.jl/issues/74
- Fixes a flaw with the debugging logging which I discovered investigating: https://github.com/invenia/Mocking.jl/issues/74
- Drop the use of Appveyor in favor of using Travis. I am testing 32-bit against Linux instead of Windows and only testing the unmaintained Julia version (1.1 and 1.2) against Linux 64-bit only.

### CODE REVIEW

**Comment by omus** [comment]
I'll need to remove the Appveyor check from this repo

**Comment by oxinabox** [comment]
Why drop AV? It lets for more tests to be run in parallel

**Comment by omus** [comment]
> Why drop AV? It lets for more tests to be run in parallel

Sort of. I ran some tests to get some actual numbers on how long the CI takes when we use both Travis CI and AppVeyor vs. only Travis CI. Test setup is as follows:

Mixed:
- Travis CI: Julia 1.0, 1.1, 1.2, nightly on Linux and macOS
- AppVeyor: Julia 1.0, 1.1, 1.2, nightly on Windows 64-bit and Windows 32-bit

Travis Only:
- Travis CI: Julia 1.0, 1.1, 1.2, nightly on Linux, macOS, Windows 64-bit, and Windows 32-bit

(PR): Indicates that two builds were submitted at once emulating the PR and branch pipelines created in pull requests

| Test             | Travis CI | AppVeyor | Total | Notes |
|:-----------------|:----------|:---------|:------|:------|
| Mixed            | 14:26     | 11:50    | 14:26 | Travis didn't start for 3 minutes | 
| Mixed            | 10:26     | 12:11    | 12:11 | Maximum concurrency for Travis CI |
| Travis Only      | 11:36     | n/a      | 11:36 | Maximum concurrency for Travis CI |
| Mixed (PR)       | 16:39     | 25:20    | 25:20 | |
| Travis Only (PR) | 20:47     | n/a      | 20:47 | |

From my observations I can summarize as follows: with maximum concurrency available using Travis CI only results in faster completion time. However in scenarios where multiple pipelines are running in the same GitHub organization the Travis CI job may not start immediately making the time to first job completion take longer. Ultimately, it appears the choice here comes down to what you want to optimize for: time to first failure or time to merge. If code is tested locally before pushing then 

Additional considerations
- Having Windows jobs in Travis CI means that Windows is also with our nightly builds
- Travis CI macOS jobs seem limited to running 2 concurrently where as Windows doesn't seem to have this limit
- Mocking.jl avoids running coverage reporting on AppVeyor which wasn't done with Travis CI Windows jobs.

**Comment by oxinabox** [comment]
Makes sense.

**Comment by iamed2** [comment]
> However in scenarios where multiple pipelines are running in the same GitHub organization the Travis CI job may not start immediately making the time to first job completion take longer.

If that is happening, then AppVeyor will have the same issue but worse, since it has only one concurrent job per org.

**Pull request merged**
